-- CreateTable
CREATE TABLE "Seat" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "seat_identifier" INT4 NOT NULL,
    "seat_class" STRING NOT NULL,
    "bookingId" INT4,

    CONSTRAINT "Seat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SeatClass" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "seat_class" STRING NOT NULL,
    "min_price" INT4 NOT NULL,
    "normal_price" INT4 NOT NULL,
    "max_price" INT4 NOT NULL,

    CONSTRAINT "SeatClass_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Booking" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "email" STRING NOT NULL,
    "phone" STRING NOT NULL,

    CONSTRAINT "Booking_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "SeatClass_seat_class_key" ON "SeatClass"("seat_class");

-- AddForeignKey
ALTER TABLE "Seat" ADD CONSTRAINT "Seat_seat_class_fkey" FOREIGN KEY ("seat_class") REFERENCES "SeatClass"("seat_class") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Seat" ADD CONSTRAINT "Seat_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE SET NULL ON UPDATE CASCADE;
